### ISSUE TITLE
Sleeping state

### ISSUE THREAD

**Issue by Johnwillliam** [hubitat/HubitatPublic#1]
Hello,

It's not an issue but more a request.
Could you add sleeping capibility to it?
I would like to send my webCoRE presence with sleep state to Hubitat.
We are trying to get everything set for the use of our Rooms app.

Thank you for your time!

Best regards,
Michael

**Comment by pstuart** [comment]
We have SleepSensor	capability.sleepSensor	
		sleeping	type:["ENUM"]	values:["not sleeping", "sleeping"]

Is that what you are referring to?

**Comment by cschwer** [comment]
No response, closing
