### ISSUE TITLE
Average Temp C/F

### ISSUE THREAD

**Issue by cjrezz** [hubitat/HubitatPublic#9]
The average Temp app properly averages temperatures in Celsius but it always puts an F by the temperature rather than a C when the user is using Celsius instead of F

**Comment by bravenel** [comment]
The app doesn't put an F in the display.  It adds ° to the log entry.  **Where are you seeing an F**?  The app is setting the temperature of a virtual device.

**Comment by bravenel** [comment]
The app doesn't put an F in the display. It adds ° to the log entry. Where are you seeing an F? The app is setting the temperature of a virtual device.

**Comment by cjrezz** [comment]
My apologies, when I went into the device I saw that there was a toggle for
F or C. I just created the average Temp and didn't realize there would be
preferences in the device it created. Great app!
